package Presentacion;

import Interfaces.IObserver;
import ModeloVista.ModeloVistaInicio;
import interfacesComunicacionModelo.IControladorInicio;
import interfacesComunicacionModelo.IModeloVistaInicio;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class JFrameSeleccionAvatar extends JFrame  implements IObserver {

    private IControladorInicio controlador;
    private String Avatar;
    private List<String> rutasAvatares = new ArrayList<>();
    private IModeloVistaInicio modeloVista;
    private int id;



    public JFrameSeleccionAvatar() {
        this(null);
    }

    public JFrameSeleccionAvatar(IControladorInicio controlador) {
    this.controlador = controlador;
    initComponents();

    // Usamos GridLayout para 3 avatares arriba y 3 abajo
    pnlAvatares.setLayout(new java.awt.GridLayout(2, 3, 20, 20));
    pnlAvatares.setPreferredSize(new Dimension(450, 300));

    // Cargar imágenes
    cargarAvatares();

    setLocationRelativeTo(null);
    setResizable(false);
}

    public IControladorInicio getControlador() {
        return controlador;
    }

    public void setControlador(IControladorInicio controlador) {
        this.controlador = controlador;
    }

    public IModeloVistaInicio getModeloVista() {
        return modeloVista;
    }

    public void setModeloVista(IModeloVistaInicio modeloVista) {
        this.modeloVista = modeloVista;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        pnlNombre = new javax.swing.JPanel();
        labelSubtitulo1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        pnlAvatares = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 250, 242));

        pnlTitulo.setBackground(new java.awt.Color(255, 250, 242));

        labelTitulo.setFont(new java.awt.Font("Sarabun", 1, 40)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CUSTOMIZAR AVATAR");

        labelSubtitulo.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo.setForeground(new java.awt.Color(51, 51, 51));
        labelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo.setText("Escribe tu nombre y selecciona tu avatar para unirte");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubtitulo))
        );

        pnlNombre.setBackground(new java.awt.Color(255, 250, 242));

        labelSubtitulo1.setFont(new java.awt.Font("Sarabun", 1, 18)); // NOI18N
        labelSubtitulo1.setForeground(new java.awt.Color(51, 51, 51));
        labelSubtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo1.setText("Ingresa tu nombre de Jugador");

        jTextField1.setBackground(new java.awt.Color(239, 231, 218));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);

        javax.swing.GroupLayout pnlNombreLayout = new javax.swing.GroupLayout(pnlNombre);
        pnlNombre.setLayout(pnlNombreLayout);
        pnlNombreLayout.setHorizontalGroup(
            pnlNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSubtitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlNombreLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        pnlNombreLayout.setVerticalGroup(
            pnlNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombreLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelSubtitulo1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnConfirmar.setBackground(new java.awt.Color(191, 233, 150));
        btnConfirmar.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(0, 42, 0));
        btnConfirmar.setText("ACEPTAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        pnlAvatares.setBackground(new java.awt.Color(255, 250, 242));
        pnlAvatares.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlAvataresLayout = new javax.swing.GroupLayout(pnlAvatares);
        pnlAvatares.setLayout(pnlAvataresLayout);
        pnlAvataresLayout.setHorizontalGroup(
            pnlAvataresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        pnlAvataresLayout.setVerticalGroup(
            pnlAvataresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)))
                .addComponent(pnlAvatares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAvatares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(pnlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
    String nombre = getNombreJugador();
    String avatar = getAvatar();

    // Validar nombre vacío
    if (nombre == null || nombre.trim().isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Por favor, ingresa un nombre de jugador.",
            "Validación",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Validar avatar no seleccionado
    if (avatar == null) {
        JOptionPane.showMessageDialog(
            this,
            "Por favor, selecciona un avatar antes de continuar.",
            "Validación",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Si todo está correcto → llamar al controlador
    if (controlador != null) {
        controlador.EnviarNombreAvatarConfirmado(id, nombre, avatar);
    } else {
        System.err.println("[ERROR] controlador es null en JFrameSeleccionAvatar");
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    public String getNombreJugador() {
        return jTextField1.getText();
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validación", JOptionPane.ERROR_MESSAGE);
    }

    private void cargarAvatares() {

    System.out.println("Entrando a cargarAvatares()...");

    pnlAvatares.removeAll(); // Limpia si recarga

    // Avatares disponibles (puedes agregar más)
    agregarAvatar("avatar1.png");
    agregarAvatar("avatar2.png");
    agregarAvatar("avatar3.png");
    agregarAvatar("avatar4.png");
    agregarAvatar("avatar5.png");
    agregarAvatar("avatar6.png");

    pnlAvatares.revalidate();
    pnlAvatares.repaint();

    System.out.println("Avatares cargados correctamente.");
}



    private void agregarAvatar(String nombreArchivo) {

    URL url = getClass().getClassLoader().getResource("img/" + nombreArchivo);

    if (url == null) {
        System.err.println("[ERROR] No se encontró la imagen: img/" + nombreArchivo);
        return;
    }

    // Crear icono desde recurso
    ImageIcon originalIcon = new ImageIcon(url);

    // Escalar imagen a tamaño uniforme
    Image img = originalIcon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
    JLabel lbl = new JLabel(new ImageIcon(img));

    lbl.setHorizontalAlignment(JLabel.CENTER);
    lbl.setVerticalAlignment(JLabel.CENTER);
    lbl.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    // Listener de selección
    lbl.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            Avatar = nombreArchivo;
            marcarSeleccion(lbl);
            System.out.println("[Avatar] Seleccionado: " + nombreArchivo);
        }
    });

    pnlAvatares.add(lbl);

    System.out.println("Avatar agregado: " + nombreArchivo);
}


private void marcarSeleccion(JLabel seleccionado) {

    for (Component comp : pnlAvatares.getComponents()) {
        if (comp instanceof JLabel lbl) {
            lbl.setBorder(null); // Quitamos borde previo
        }
    }

    // Aplicar borde verde al seleccionado
    seleccionado.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
}


    private void seleccionarAvatar(String ruta, JPanel panelSeleccionado) {

    this.Avatar = ruta;  
    System.out.println("[Avatar] Seleccionado: " + ruta);

    // Desmarcar todos
    for (Component comp : pnlAvatares.getComponents()) {
        if (comp instanceof JPanel) {
            ((JPanel) comp).setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2));
        }
    }

    // Marcar seleccionado
    panelSeleccionado.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
}

    public String getAvatar() {
        return Avatar;
    }

    public void setAvatar(String Avatar) {
        this.Avatar = Avatar;
    }
    @Override
    public void update() {
        System.out.println("");    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelSubtitulo1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel pnlAvatares;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables


}
