/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author abrilislas
 */
public class JPantallaJuego extends JFramePadre {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPantallaJuego.class.getName());

    /**
     * Creates new form JPantallaJuego
     */
    public JPantallaJuego() {
        super();
        initComponents();
        deslpegarImagenTablero();
        setLocationRelativeTo(null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        panelTableroImagen = new javax.swing.JPanel();
        panelJugadorPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelPuntaje = new javax.swing.JLabel();
        panelCartaImg = new javax.swing.JPanel();
        panelCartaTexto = new javax.swing.JPanel();
        labelNombreCartaActual = new javax.swing.JLabel();
        labelProximaCarta = new javax.swing.JLabel();
        labelTimerProximaCarta = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGritarJugada = new javax.swing.JButton();
        btnGanarLoteria = new javax.swing.JButton();
        panelJugadoresSecundarios = new javax.swing.JPanel();
        btnAbandonarPartida = new javax.swing.JButton();

        jPanelFondo.setBackground(new java.awt.Color(255, 250, 242));

        panelTableroImagen.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelTableroImagenLayout = new javax.swing.GroupLayout(panelTableroImagen);
        panelTableroImagen.setLayout(panelTableroImagenLayout);
        panelTableroImagenLayout.setHorizontalGroup(
            panelTableroImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        panelTableroImagenLayout.setVerticalGroup(
            panelTableroImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelJugadorPrincipal.setBackground(new java.awt.Color(255, 250, 242));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 55, 138));
        jLabel1.setText("Jugador 01.");

        labelPuntaje.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        labelPuntaje.setForeground(new java.awt.Color(102, 102, 102));
        labelPuntaje.setText("Puntaje: 0000.00");

        javax.swing.GroupLayout panelJugadorPrincipalLayout = new javax.swing.GroupLayout(panelJugadorPrincipal);
        panelJugadorPrincipal.setLayout(panelJugadorPrincipalLayout);
        panelJugadorPrincipalLayout.setHorizontalGroup(
            panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorPrincipalLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuntaje)
                    .addComponent(jLabel1))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        panelJugadorPrincipalLayout.setVerticalGroup(
            panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(labelPuntaje)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelCartaImg.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelCartaImgLayout = new javax.swing.GroupLayout(panelCartaImg);
        panelCartaImg.setLayout(panelCartaImgLayout);
        panelCartaImgLayout.setHorizontalGroup(
            panelCartaImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        panelCartaImgLayout.setVerticalGroup(
            panelCartaImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        panelCartaTexto.setBackground(new java.awt.Color(255, 250, 242));

        labelNombreCartaActual.setFont(new java.awt.Font("Sarabun", 1, 34)); // NOI18N
        labelNombreCartaActual.setText("La Estrella ");

        labelProximaCarta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelProximaCarta.setForeground(new java.awt.Color(102, 0, 0));
        labelProximaCarta.setText("Próxima carta en:");

        labelTimerProximaCarta.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTimerProximaCarta.setForeground(new java.awt.Color(255, 102, 102));
        labelTimerProximaCarta.setText("00:00");

        javax.swing.GroupLayout panelCartaTextoLayout = new javax.swing.GroupLayout(panelCartaTexto);
        panelCartaTexto.setLayout(panelCartaTextoLayout);
        panelCartaTextoLayout.setHorizontalGroup(
            panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaTextoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCartaTextoLayout.createSequentialGroup()
                        .addComponent(labelProximaCarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTimerProximaCarta))
                    .addComponent(labelNombreCartaActual))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelCartaTextoLayout.setVerticalGroup(
            panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaTextoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelNombreCartaActual)
                .addGap(11, 11, 11)
                .addGroup(panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProximaCarta)
                    .addComponent(labelTimerProximaCarta))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(255, 250, 242));

        btnGritarJugada.setBackground(new java.awt.Color(130, 172, 255));
        btnGritarJugada.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnGritarJugada.setForeground(new java.awt.Color(5, 0, 136));
        btnGritarJugada.setText("Gritar");
        btnGritarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGritarJugadaActionPerformed(evt);
            }
        });

        btnGanarLoteria.setBackground(new java.awt.Color(191, 233, 150));
        btnGanarLoteria.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnGanarLoteria.setForeground(new java.awt.Color(0, 42, 0));
        btnGanarLoteria.setText("¡LOTERÍA!");
        btnGanarLoteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanarLoteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGritarJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGanarLoteria, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGritarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGanarLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelJugadoresSecundarios.setBackground(new java.awt.Color(255, 250, 242));
        panelJugadoresSecundarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelJugadoresSecundariosLayout = new javax.swing.GroupLayout(panelJugadoresSecundarios);
        panelJugadoresSecundarios.setLayout(panelJugadoresSecundariosLayout);
        panelJugadoresSecundariosLayout.setHorizontalGroup(
            panelJugadoresSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        panelJugadoresSecundariosLayout.setVerticalGroup(
            panelJugadoresSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        btnAbandonarPartida.setBackground(new java.awt.Color(229, 133, 133));
        btnAbandonarPartida.setFont(new java.awt.Font("Sarabun", 1, 16)); // NOI18N
        btnAbandonarPartida.setForeground(new java.awt.Color(153, 0, 0));
        btnAbandonarPartida.setText("ABANDONAR PARTIDA");
        btnAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelTableroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(panelCartaImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCartaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugadoresSecundarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJugadoresSecundarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTableroImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFondoLayout.createSequentialGroup()
                                .addComponent(panelCartaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelCartaImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGanarLoteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanarLoteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanarLoteriaActionPerformed

    private void btnGritarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGritarJugadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGritarJugadaActionPerformed

    private void btnAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JPantallaJuego().setVisible(true));
    }
    private void deslpegarImagenTablero(){
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/Tablero01.png"));

        Image imgEscalada = iconoOriginal.getImage().getScaledInstance(
                panelTableroImagen.getWidth(),
                panelTableroImagen.getHeight(),
                Image.SCALE_SMOOTH
        );

        JLabel labelTablero = new JLabel(new ImageIcon(imgEscalada));
        labelTablero.setSize(panelTableroImagen.getSize());

        panelTableroImagen.setLayout(new BorderLayout());
        panelTableroImagen.add(labelTablero, BorderLayout.CENTER);

        panelTableroImagen.revalidate();
        panelTableroImagen.repaint();
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarPartida;
    private javax.swing.JButton btnGanarLoteria;
    private javax.swing.JButton btnGritarJugada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JLabel labelNombreCartaActual;
    private javax.swing.JLabel labelProximaCarta;
    private javax.swing.JLabel labelPuntaje;
    private javax.swing.JLabel labelTimerProximaCarta;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCartaImg;
    private javax.swing.JPanel panelCartaTexto;
    private javax.swing.JPanel panelJugadorPrincipal;
    private javax.swing.JPanel panelJugadoresSecundarios;
    private javax.swing.JPanel panelTableroImagen;
    // End of variables declaration//GEN-END:variables
}
