
package Presentacion;

import Controlador.ControlSeleccionarCarta;
import ModeloVista.ModeloVista;
import ModeloVista.entidadesVista.CartaVista;
import ModeloVista.entidadesVista.JugadorVista;
import Observer.Observer;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author abrilislas
 */
public class JPantallaJuego extends JFramePadre implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPantallaJuego.class.getName());
    private ModeloVista modeloVista;
    /**
     * Creates new form JPantallaJuego
     */
    public JPantallaJuego(ModeloVista modeloVista, ControlSeleccionarCarta controlador) {
        super();
        this.modeloVista = modeloVista;
        this.modeloVista.addObserver(this);
        initComponents();
        panelTableroImagen.setPreferredSize(new java.awt.Dimension(350, 250)); // tamaño mínimo visible
        inicializarTableroConMatriz(); // en lugar de deslpegarImagenTablero()
        setLocationRelativeTo(null);
        setResizable(false); // Evita que el usuario cambie el tamaño del JFrame
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        panelTableroImagen = new javax.swing.JPanel();
        panelJugadorPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelPuntaje = new javax.swing.JLabel();
        panelCartaImg = new javax.swing.JPanel();
        panelCartaTexto = new javax.swing.JPanel();
        labelNombreCartaActual = new javax.swing.JLabel();
        labelProximaCarta = new javax.swing.JLabel();
        labelTimerProximaCarta = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGritarJugada = new javax.swing.JButton();
        btnGanarLoteria = new javax.swing.JButton();
        panelJugadoresSecundarios = new javax.swing.JPanel();
        btnAbandonarPartida = new javax.swing.JButton();

        jPanelFondo.setBackground(new java.awt.Color(255, 250, 242));

        panelTableroImagen.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelTableroImagenLayout = new javax.swing.GroupLayout(panelTableroImagen);
        panelTableroImagen.setLayout(panelTableroImagenLayout);
        panelTableroImagenLayout.setHorizontalGroup(
            panelTableroImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        panelTableroImagenLayout.setVerticalGroup(
            panelTableroImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelJugadorPrincipal.setBackground(new java.awt.Color(255, 250, 242));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 55, 138));
        jLabel1.setText("Jugador 01.");

        labelPuntaje.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        labelPuntaje.setForeground(new java.awt.Color(102, 102, 102));
        labelPuntaje.setText("Puntaje: 0000.00");

        javax.swing.GroupLayout panelJugadorPrincipalLayout = new javax.swing.GroupLayout(panelJugadorPrincipal);
        panelJugadorPrincipal.setLayout(panelJugadorPrincipalLayout);
        panelJugadorPrincipalLayout.setHorizontalGroup(
            panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorPrincipalLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuntaje)
                    .addComponent(jLabel1))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        panelJugadorPrincipalLayout.setVerticalGroup(
            panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(labelPuntaje)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelCartaImg.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelCartaImgLayout = new javax.swing.GroupLayout(panelCartaImg);
        panelCartaImg.setLayout(panelCartaImgLayout);
        panelCartaImgLayout.setHorizontalGroup(
            panelCartaImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        panelCartaImgLayout.setVerticalGroup(
            panelCartaImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        panelCartaTexto.setBackground(new java.awt.Color(255, 250, 242));

        labelNombreCartaActual.setFont(new java.awt.Font("Sarabun", 1, 34)); // NOI18N
        labelNombreCartaActual.setText("La Estrella ");

        labelProximaCarta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelProximaCarta.setForeground(new java.awt.Color(102, 0, 0));
        labelProximaCarta.setText("Próxima carta en:");

        labelTimerProximaCarta.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTimerProximaCarta.setForeground(new java.awt.Color(255, 102, 102));
        labelTimerProximaCarta.setText("00:00");

        javax.swing.GroupLayout panelCartaTextoLayout = new javax.swing.GroupLayout(panelCartaTexto);
        panelCartaTexto.setLayout(panelCartaTextoLayout);
        panelCartaTextoLayout.setHorizontalGroup(
            panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaTextoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCartaTextoLayout.createSequentialGroup()
                        .addComponent(labelProximaCarta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTimerProximaCarta))
                    .addComponent(labelNombreCartaActual))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelCartaTextoLayout.setVerticalGroup(
            panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaTextoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelNombreCartaActual)
                .addGap(11, 11, 11)
                .addGroup(panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProximaCarta)
                    .addComponent(labelTimerProximaCarta))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(255, 250, 242));

        btnGritarJugada.setBackground(new java.awt.Color(130, 172, 255));
        btnGritarJugada.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnGritarJugada.setForeground(new java.awt.Color(5, 0, 136));
        btnGritarJugada.setText("Gritar");
        btnGritarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGritarJugadaActionPerformed(evt);
            }
        });

        btnGanarLoteria.setBackground(new java.awt.Color(191, 233, 150));
        btnGanarLoteria.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnGanarLoteria.setForeground(new java.awt.Color(0, 42, 0));
        btnGanarLoteria.setText("¡LOTERÍA!");
        btnGanarLoteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanarLoteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGritarJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGanarLoteria, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGritarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGanarLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelJugadoresSecundarios.setBackground(new java.awt.Color(255, 250, 242));
        panelJugadoresSecundarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelJugadoresSecundariosLayout = new javax.swing.GroupLayout(panelJugadoresSecundarios);
        panelJugadoresSecundarios.setLayout(panelJugadoresSecundariosLayout);
        panelJugadoresSecundariosLayout.setHorizontalGroup(
            panelJugadoresSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        panelJugadoresSecundariosLayout.setVerticalGroup(
            panelJugadoresSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        btnAbandonarPartida.setBackground(new java.awt.Color(229, 133, 133));
        btnAbandonarPartida.setFont(new java.awt.Font("Sarabun", 1, 16)); // NOI18N
        btnAbandonarPartida.setForeground(new java.awt.Color(153, 0, 0));
        btnAbandonarPartida.setText("ABANDONAR PARTIDA");
        btnAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelTableroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(panelCartaImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCartaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugadoresSecundarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJugadoresSecundarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTableroImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFondoLayout.createSequentialGroup()
                                .addComponent(panelCartaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelCartaImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGanarLoteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanarLoteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanarLoteriaActionPerformed

    private void btnGritarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGritarJugadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGritarJugadaActionPerformed

    private void btnAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarPartidaActionPerformed



private void actualizarCartaCantada() {
    CartaVista cartaActual = modeloVista.getCartaCantada();
    if (cartaActual != null) {
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(cartaActual.getRuta()));
        Image imgEscalada = iconoOriginal.getImage().getScaledInstance(
                panelCartaImg.getWidth(),
                panelCartaImg.getHeight(),
                Image.SCALE_SMOOTH
        );

        // En lugar de removeAll(), reutiliza un JLabel fijo
        if (panelCartaImg.getComponentCount() == 0 || !(panelCartaImg.getComponent(0) instanceof JLabel)) {
            panelCartaImg.removeAll();
            JLabel labelCarta = new JLabel();
            labelCarta.setHorizontalAlignment(SwingConstants.CENTER);
            panelCartaImg.setLayout(new BorderLayout());
            panelCartaImg.add(labelCarta, BorderLayout.CENTER);
        }

        JLabel labelCarta = (JLabel) panelCartaImg.getComponent(0);
        labelCarta.setIcon(new ImageIcon(imgEscalada));
        labelNombreCartaActual.setText(cartaActual.getNombreCarta());

        panelCartaImg.revalidate();
        panelCartaImg.repaint();
    }
}

   @Override
public void update() {
    // Procesar las casillas marcadas del jugador
    procesarCasillasMarcadas();

    // Actualizar la carta cantada
    actualizarCartaCantada();
}
        // --- clase interna para mostrar la imagen escalada ---
private static class ScaledImageComponent extends javax.swing.JComponent {
    private final java.awt.Image image;
    public ScaledImageComponent(java.awt.Image img) {
        this.image = img;
        setOpaque(false);
    }
    
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            int w = getWidth();
            int h = getHeight();
            g.drawImage(image, 0, 0, w, h, this);
        }
    }
}

private javax.swing.JLayeredPane layeredTablero;
private javax.swing.JButton[][] botonesMatriz; // opcional para acceder luego

private void inicializarTableroConMatriz() {
    // Cargar la imagen de fondo una vez al iniciar
    java.net.URL url = getClass().getResource("/img/Tableros/Tablero01.png");
    if (url == null) {
        System.err.println("No se encontró la imagen /img/Tableros/Tablero01.png");
        return;
    }
    java.awt.Image img = new javax.swing.ImageIcon(url).getImage();
    ScaledImageComponent fondo = new ScaledImageComponent(img);

    // Panel con GridLayout 4x4 para los botones
    JPanel panelMatriz = new JPanel(new java.awt.GridLayout(4, 4));
    panelMatriz.setOpaque(false);

    botonesMatriz = new javax.swing.JButton[4][4];
    for (int r = 0; r < 4; r++) {
        for (int c = 0; c < 4; c++) {
            final int rf = r, cf = c;
            JButton btn = new JButton();
            // Apariencia transparente, sin imágenes
            btn.setRolloverEnabled(false);

            btn.setIcon(null);
            btn.setContentAreaFilled(false);
            btn.setBorderPainted(false);
            btn.setOpaque(false);

            // Acción al hacer clic usando el controlador del constructor
            btn.addActionListener(e -> {
                int posicion = (rf * 4) + cf + 1;
                ControlSeleccionarCarta controlador = new ControlSeleccionarCarta(modeloVista);
                controlador.seleccionarCarta(posicion);
                System.out.println("Carta seleccionada: " + posicion);
            });

            botonesMatriz[r][c] = btn;
            panelMatriz.add(btn);
        }
    }

    // Configurar JLayeredPane
    layeredTablero = new JLayeredPane();
    layeredTablero.setOpaque(false);

    // Limpiar y añadir al panel
    panelTableroImagen.removeAll();
    panelTableroImagen.setLayout(new BorderLayout());
    panelTableroImagen.add(layeredTablero, BorderLayout.CENTER);

    // Añadir componentes al layeredPane (fondo estático)
    layeredTablero.add(fondo, JLayeredPane.DEFAULT_LAYER);
    layeredTablero.add(panelMatriz, JLayeredPane.PALETTE_LAYER);

    // Ajuste de tamaño solo para mantener proporciones, sin repaint
    panelTableroImagen.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            int w = panelTableroImagen.getWidth();
            int h = panelTableroImagen.getHeight();
            layeredTablero.setBounds(0, 0, w, h);
            fondo.setBounds(0, 0, w, h);
            panelMatriz.setBounds(0, 0, w, h);
        }
    });

    java.awt.EventQueue.invokeLater(() -> {
        
        int w = panelTableroImagen.getWidth();
        int h = panelTableroImagen.getHeight();
        if (w > 0 && h > 0) {
            layeredTablero.setBounds(0, 0, w, h);
            fondo.setBounds(0, 0, w, h);
            panelMatriz.setBounds(0, 0, w, h);
        }
    }
    );
}


public void actualizarCartasCorrectas(boolean[] cartasCorrectas) {
    if (cartasCorrectas == null || cartasCorrectas.length != 16) {
        return;
    }
    for (int posicion = 0; posicion < 16; posicion++) {
        int fila = posicion / 4;
        int columna = posicion % 4;
        JButton btn = botonesMatriz[fila][columna];
        if (btn != null) {
            java.awt.Color currentColor = btn.getBackground(); // Para referencia, aunque no se usará setBackground
            if (cartasCorrectas[posicion]) {
                // Crear o mostrar un panel interno verde si no está visible
                if (btn.getComponentCount() == 0) {
                    JPanel colorPanel = new JPanel();
                    colorPanel.setBackground(new java.awt.Color(0, 255, 0, 128));
                    colorPanel.setOpaque(true);
                    btn.setLayout(new java.awt.BorderLayout());
                    btn.add(colorPanel, java.awt.BorderLayout.CENTER);
                } else if (!btn.getComponent(0).isVisible()) {
                    btn.getComponent(0).setVisible(true);
                }
                System.out.println("Pintando casilla " + (posicion + 1) + " de verde");
            } else {
                // Ocultar el panel interno si existe y la casilla no está marcada
                if (btn.getComponentCount() > 0 && btn.getComponent(0).isVisible()) {
                    btn.getComponent(0).setVisible(false);
                    System.out.println("Restaurando casilla " + (posicion + 1) + " a transparente");
                }
            }
        }
    }
}
private void procesarCasillasMarcadas() {
    JugadorVista jugadorPrincipal = modeloVista.getJugadorPrincipal();
    if (jugadorPrincipal != null) {
        boolean[] casillasMarcadas = jugadorPrincipal.getTarjeta().getMarcadas();
        actualizarCartasCorrectas(casillasMarcadas);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarPartida;
    private javax.swing.JButton btnGanarLoteria;
    private javax.swing.JButton btnGritarJugada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JLabel labelNombreCartaActual;
    private javax.swing.JLabel labelProximaCarta;
    private javax.swing.JLabel labelPuntaje;
    private javax.swing.JLabel labelTimerProximaCarta;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCartaImg;
    private javax.swing.JPanel panelCartaTexto;
    private javax.swing.JPanel panelJugadorPrincipal;
    private javax.swing.JPanel panelJugadoresSecundarios;
    private javax.swing.JPanel panelTableroImagen;
    // End of variables declaration//GEN-END:variables
}
