package Presentacion;

import ModeloVista.ModeloVista;
import Observer.Observer;

public class JPanelJugadorPrincipal extends javax.swing.JPanel implements Observer {
    private ModeloVista modeloVista;
    public JPanelJugadorPrincipal(ModeloVista modeloVista) {
        initComponents();
        this.modeloVista = modeloVista;
        this.modeloVista.addObserver(this);
        cargarNombre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreJugadorPrincipal = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 250, 242));

        lblNombreJugadorPrincipal.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblNombreJugadorPrincipal.setForeground(new java.awt.Color(79, 55, 138));
        lblNombreJugadorPrincipal.setText("Jugador 01.");

        lblPuntaje.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(102, 102, 102));
        lblPuntaje.setText("Puntaje: 0000.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntaje)
                    .addComponent(lblNombreJugadorPrincipal))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblNombreJugadorPrincipal)
                .addGap(13, 13, 13)
                .addComponent(lblPuntaje)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update() {
        //codigo para actualizar puntaje
    }
    
    private void cargarNombre(){
        System.out.println(modeloVista.getJugadorPrincipal().getNombre());
        lblNombreJugadorPrincipal.setText(modeloVista.getJugadorPrincipal().getNombre());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombreJugadorPrincipal;
    private javax.swing.JLabel lblPuntaje;
    // End of variables declaration//GEN-END:variables
}
