package Presentacion;

import Controlador.ControlSeleccionarCarta;
import ModeloVista.ModeloVista;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author abrilislas
 */
public class PanelTarjeta extends javax.swing.JPanel {
    
    /**
     * VARIABLES FINALES DE LAS PROPORCIONES DE LAS CASILLAS
     */
    private final int FILAS = 4; // Filas de las tarjetas.
    private final int COLUMNAS = 4; // Columnas de la tarjeta.
    private final int ESPACIADO = 5; //Espaciado
    
    private ModeloVista modeloVista;
    
    // Listener para validar la selección
    ActionListener validarSeleccion = e -> {
    JButton boton = (JButton) e.getSource();
    Integer numCarta = (Integer) boton.getClientProperty("numCarta");
    JPanel overlay = (JPanel) boton.getClientProperty("overlay");

            if (numCarta == null || overlay ==null) {
                System.err.println("Los datos de la carta no se encontraron.");
                return;
            }
                ControlSeleccionarCarta controlador = new ControlSeleccionarCarta(modeloVista); //Instancia del controlador
                controlador.seleccionarCarta(numCarta, boton);// Envía la posición al control 
                System.out.println("Carta seleccionada: " + numCarta); //Imprime la posición
        };
    
    public PanelTarjeta(int[] arregloCartas, ActionListener listenerClickCasilla) {
        setLayout(new GridLayout(FILAS, COLUMNAS, ESPACIADO, ESPACIADO));
        setPreferredSize(new Dimension(370, 522)); 
        
        //tratamos de crear todas las casillas de la tarjeta
        try {
            //invocamos a la fabrica de casillas
            new FabricaCasillaTablero(arregloCartas, this, listenerClickCasilla);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las imágenes del tablero: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
