/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import ModeloVista.ModeloVista;
import ModeloVista.entidadesVista.JugadorVista;
import Observer.Observer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author abrilislas
 */
public class PanelJugadorSecundario extends javax.swing.JPanel implements Observer {
    
    private JugadorVista jugador;
    private ModeloVista modeloVista;
    private JPanel[] panelCasillasGrid;

    /**
     * Creates new form PanelJugadorSecundario
     */
    public PanelJugadorSecundario(JugadorVista jugador, ModeloVista modeloVista) {
        initComponents();
        this.jugador = jugador;
        this.modeloVista = modeloVista;
        this.modeloVista.addObserver(this);
        lblNombre.setText(jugador.getNombre());
        cargarAvatar();
        this.panelCasillasGrid = new JPanel[16];
        
        //construimos cada uno de los paneles individuales y se agregan al panel con el grid 4x4
        for (int i = 0; i < 16; i++) {
            JPanel casilla = new JPanel();
            casilla.setPreferredSize(new Dimension(38, 28));
            casilla.setBackground(new Color(203, 191, 168));
            casilla.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
            pnlCasillas.add(casilla);
            panelCasillasGrid[i] = casilla;
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        pnlCasillas = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 250, 242));

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(79, 55, 138));
        lblNombre.setText("Jugador 01.");

        lblPuntaje.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(102, 102, 102));
        lblPuntaje.setText("Puntaje: 0000.00");

        lblAvatar.setBackground(new java.awt.Color(255, 255, 255));

        pnlCasillas.setBackground(new java.awt.Color(203, 191, 168));
        pnlCasillas.setLayout(new java.awt.GridLayout(4, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuntaje)
                            .addComponent(lblNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(pnlCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntaje)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizar(JugadorVista jugador) {
        lblPuntaje.setText("Puntaje: " + jugador.getPuntaje());
        boolean[] marcadas = jugador.getTarjeta().getMarcadas();

        for (int i = 0; i < panelCasillasGrid.length; i++) {
            JPanel casilla = panelCasillasGrid[i];

            casilla.setPreferredSize(new Dimension(38, 28));

            casilla.setBackground(new Color(203,191,168));  

            if (marcadas[i]) {
                casilla.setBackground(new Color(255,144,144));
            }

            casilla.revalidate();
            casilla.repaint();
    }

    pnlCasillas.revalidate();
    pnlCasillas.repaint();
}

    @Override
    public void update() {
        actualizar(jugador);
    }
    
        private void cargarAvatar() {
        String rutaAvatar = jugador.getRutaAvatar();
        if (rutaAvatar != null) {
            java.net.URL url = getClass().getResource(rutaAvatar);
            if (url != null) {
                ImageIcon icono = new ImageIcon(url);

                Image imagenEscalada = icono.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                lblAvatar.setIcon(new ImageIcon(imagenEscalada));
            } else {
                System.out.println("No se encontró la imagen: " + rutaAvatar);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JPanel pnlCasillas;
    // End of variables declaration//GEN-END:variables
}
