/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import ModeloVista.entidadesVista.JugadorVista;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author isaac
 */
public class JPantallaFinJuego extends javax.swing.JDialog {
    

    /**
     * Creates new form JPantallaFinJuego
     */
    public JPantallaFinJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        pnlRanking.setLayout(new BoxLayout(pnlRanking, BoxLayout.Y_AXIS));

    }

    private JPanel crearFilaJugador(int top, JugadorVista jugador) {

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        panel.setMaximumSize(new Dimension(350, 60));

        JLabel lblNombre = new JLabel();
        String texto = String.format("Top %d: %s (%s pts)", top, jugador.getNombre(), jugador.getPuntaje());
        lblNombre.setText(texto);
        lblNombre.setFont(new Font("Arial", Font.BOLD, 14));
        lblNombre.setForeground(Color.BLACK);
        // Reservamos espacio fijo para el texto para que la imagen siempre quede a la derecha
        lblNombre.setPreferredSize(new Dimension(220, 50));

        // 3. Configuración de la Imagen (Avatar)
        JLabel lblAvatar = new JLabel();
        lblAvatar.setPreferredSize(new Dimension(40, 40)); // Tamaño fijo del contenedor de imagen
        lblAvatar.setHorizontalAlignment(SwingConstants.CENTER);

        // --- LÓGICA DE CARGA DE IMAGEN ---
        try {
            // El controlador ya debió setear algo como "/img/Avatares/user1.png"
            String rutaImagen = jugador.getRutaAvatar();

            if (rutaImagen != null && !rutaImagen.isEmpty()) {
                // Buscamos el recurso en el classpath
                java.net.URL imgURL = getClass().getResource(rutaImagen);

                if (imgURL != null) {
                    // Cargamos la imagen original
                    ImageIcon iconOriginal = new ImageIcon(imgURL);

                    // La redimensionamos suavemente a 40x40 pixeles
                    Image imgEscalada = iconOriginal.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);

                    // La asignamos al Label
                    lblAvatar.setIcon(new ImageIcon(imgEscalada));
                } else {
                    // Si la ruta no existe (archivo perdido), ponemos texto de error
                    System.err.println("No se encontró la imagen en: " + rutaImagen);
                    lblAvatar.setText("?");
                    lblAvatar.setForeground(Color.RED);
                }
            } else {
                lblAvatar.setText("-"); // Sin ruta asignada
            }
        } catch (Exception e) {
            System.err.println("Error al cargar avatar para " + jugador.getNombre() + ": " + e.getMessage());
            lblAvatar.setText("Err");
        }

        //   Agregar componentes al panel fila
        panel.add(lblNombre);
        panel.add(lblAvatar);

        return panel;
    }

    public void mostrarRanking(List<JugadorVista> ranking) {
        if (ranking != null && !ranking.isEmpty()) {
            JugadorVista ganador = ranking.get(0);
            lblGanador.setText(ganador.getNombre().toUpperCase() + " HA GANADO LA PARTIDA!");
        }

        //  Limpiar el panel por si acaso
        pnlRanking.removeAll();

        // Generar dinamicamente las filas del Top
        for (int i = 0; i < ranking.size(); i++) {
            JugadorVista jugador = ranking.get(i);
            int posicion = i + 1; // Top 1, Top 2...

            // Crear un panel para la fila
            JPanel fila = crearFilaJugador(posicion, jugador);

            // Agregarlo al contenedor visual
            pnlRanking.add(fila);

            // Agregar un pequeño espacio entre filas
            pnlRanking.add(Box.createRigidArea(new Dimension(0, 10)));
        }

        // Refrescar la interfaz para que aparezcan los cambios
        pnlRanking.revalidate();
        pnlRanking.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        lblGanador = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        pnlRanking = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("FIN DE LA PARTIDA");

        lblGanador.setText("EL GANADOR DE LA PARTIDA ES:");

        btnAceptar.setBackground(new java.awt.Color(191, 233, 150));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo))
                .addGap(0, 83, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblGanador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(63, 63, 63)
                .addComponent(lblGanador)
                .addGap(30, 30, 30)
                .addComponent(pnlRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPantallaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPantallaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPantallaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPantallaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JPantallaFinJuego dialog = new JPantallaFinJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JScrollPane pnlRanking;
    // End of variables declaration//GEN-END:variables
}
