package Presentacion;

import Controlador.ControlSeleccionarCarta;
import Controlador.ControlVista;
import ModeloVista.entidadesVista.JugadorVista;
import Interfaces.IModeloVista;
import Interfaces.IOyenteVista;
import Interfaces.Observer;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * JFrame principal del juego de Lotería. Contiene la interfaz completa: tablero
 * del jugador principal, carta actual, nombre de la carta cantada, botones de
 * acción, y panel de jugadores secundarios. Implementa Observer para actualizar
 * la vista cuando el ModeloVista notifica cambios.
 */
public class JPantallaJuego extends JFramePadre implements Observer {

    private IModeloVista modeloVista;
    private IOyenteVista oyenteAccion;
    private JDialog dialogoEspera;

    public JPantallaJuego(IModeloVista modeloVista, ControlSeleccionarCarta controlador) {
        super();
        this.modeloVista = modeloVista;
        this.modeloVista.addObserver(this);

        initComponents();           // Inicializa componentes generados por NetBeans
        setLocationRelativeTo(null);
        setResizable(false);        // Evita que el usuario cambie el tamaño

        crearPanelTarjeta();        // Panel de tarjeta del jugador principal
        crearPanelCarta();          // Panel de carta cantada
        crearPanelJugadorPrincipal(); // Panel jugador principal
        cargarJugadoresSecundarios(); // Panel jugadores secundarios

    }

    public void setOyente(IOyenteVista oyente) {
        this.oyenteAccion = oyente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        panelTableroImagen = new javax.swing.JPanel();
        panelJugadorPrincipal = new javax.swing.JPanel();
        panelCartaImg = new javax.swing.JPanel();
        panelCartaTexto = new javax.swing.JPanel();
        labelNombreCartaActual = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGritarJugada = new javax.swing.JButton();
        btnIntentoLoteria = new javax.swing.JButton();
        panelJugadoresSecundarios = new javax.swing.JPanel();
        btnAbandonarPartida = new javax.swing.JButton();

        jPanelFondo.setBackground(new java.awt.Color(255, 250, 242));

        panelTableroImagen.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelTableroImagenLayout = new javax.swing.GroupLayout(panelTableroImagen);
        panelTableroImagen.setLayout(panelTableroImagenLayout);
        panelTableroImagenLayout.setHorizontalGroup(
            panelTableroImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        panelTableroImagenLayout.setVerticalGroup(
            panelTableroImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelJugadorPrincipal.setBackground(new java.awt.Color(255, 250, 242));

        javax.swing.GroupLayout panelJugadorPrincipalLayout = new javax.swing.GroupLayout(panelJugadorPrincipal);
        panelJugadorPrincipal.setLayout(panelJugadorPrincipalLayout);
        panelJugadorPrincipalLayout.setHorizontalGroup(
            panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        panelJugadorPrincipalLayout.setVerticalGroup(
            panelJugadorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        panelCartaImg.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelCartaImgLayout = new javax.swing.GroupLayout(panelCartaImg);
        panelCartaImg.setLayout(panelCartaImgLayout);
        panelCartaImgLayout.setHorizontalGroup(
            panelCartaImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        panelCartaImgLayout.setVerticalGroup(
            panelCartaImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        panelCartaTexto.setBackground(new java.awt.Color(255, 250, 242));

        labelNombreCartaActual.setFont(new java.awt.Font("Sarabun", 1, 34)); // NOI18N
        labelNombreCartaActual.setText("La Estrella ");

        javax.swing.GroupLayout panelCartaTextoLayout = new javax.swing.GroupLayout(panelCartaTexto);
        panelCartaTexto.setLayout(panelCartaTextoLayout);
        panelCartaTextoLayout.setHorizontalGroup(
            panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaTextoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelNombreCartaActual)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelCartaTextoLayout.setVerticalGroup(
            panelCartaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaTextoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelNombreCartaActual)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(255, 250, 242));

        btnGritarJugada.setBackground(new java.awt.Color(130, 172, 255));
        btnGritarJugada.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnGritarJugada.setForeground(new java.awt.Color(5, 0, 136));
        btnGritarJugada.setText("Gritar");
        btnGritarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGritarJugadaActionPerformed(evt);
            }
        });

        btnIntentoLoteria.setBackground(new java.awt.Color(191, 233, 150));
        btnIntentoLoteria.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnIntentoLoteria.setForeground(new java.awt.Color(0, 42, 0));
        btnIntentoLoteria.setText("¡LOTERÍA!");
        btnIntentoLoteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentoLoteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGritarJugada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIntentoLoteria, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGritarJugada, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIntentoLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelJugadoresSecundarios.setBackground(new java.awt.Color(255, 250, 242));
        panelJugadoresSecundarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelJugadoresSecundariosLayout = new javax.swing.GroupLayout(panelJugadoresSecundarios);
        panelJugadoresSecundarios.setLayout(panelJugadoresSecundariosLayout);
        panelJugadoresSecundariosLayout.setHorizontalGroup(
            panelJugadoresSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelJugadoresSecundariosLayout.setVerticalGroup(
            panelJugadoresSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        btnAbandonarPartida.setBackground(new java.awt.Color(229, 133, 133));
        btnAbandonarPartida.setFont(new java.awt.Font("Sarabun", 1, 16)); // NOI18N
        btnAbandonarPartida.setForeground(new java.awt.Color(153, 0, 0));
        btnAbandonarPartida.setText("ABANDONAR PARTIDA");
        btnAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelTableroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(panelCartaImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCartaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(panelJugadoresSecundarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJugadoresSecundarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTableroImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(panelJugadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFondoLayout.createSequentialGroup()
                                .addComponent(panelCartaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelCartaImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(btnAbandonarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntentoLoteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentoLoteriaActionPerformed

        if (oyenteAccion != null) {
            oyenteAccion.solicitarIntentoLoteria();
        }
    }//GEN-LAST:event_btnIntentoLoteriaActionPerformed

    private void btnGritarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGritarJugadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGritarJugadaActionPerformed

    private void btnAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbandonarPartidaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonarPartida;
    private javax.swing.JButton btnGritarJugada;
    private javax.swing.JButton btnIntentoLoteria;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JLabel labelNombreCartaActual;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCartaImg;
    private javax.swing.JPanel panelCartaTexto;
    private javax.swing.JPanel panelJugadorPrincipal;
    private javax.swing.JPanel panelJugadoresSecundarios;
    private javax.swing.JPanel panelTableroImagen;
    // End of variables declaration//GEN-END:variables

    /**
     * Método llamado cuando el ModeloVista notifica un cambio. Actualmente no
     * realiza acción directa, pero puede actualizar UI futura.
     */
    @Override
    public void update() {

        // ---------------------------------------------------------
        // 1. PRIORIDAD: FIN DE PARTIDA (Ranking)
        // ---------------------------------------------------------
        if (modeloVista.isJuegoTerminado()) {

            if (dialogoEspera != null) {
                dialogoEspera.dispose();
            }

            JPantallaFinJuego dialogFinPartida = new JPantallaFinJuego(this, true);
            dialogFinPartida.mostrarRanking(modeloVista.getListaRanking());
            this.dispose();
            dialogFinPartida.setVisible(true);
            return;
        }

        // ---------------------------------------------------------
        // 2. FIN DE RONDA (Mostrar Alerta)
        // ---------------------------------------------------------
        if (modeloVista.isFinDeRonda()) {

            String ganadorRonda = modeloVista.getGanadorRonda();
            int ronda = modeloVista.getNumRonda();

            // Solo mostramos si no está visible ya (para evitar que parpadee o se duplique)
            if (dialogoEspera == null || !dialogoEspera.isVisible()) {
                mostrarJOptionPaneFinRonda(ronda, ganadorRonda);
            }
        }  
         
        else if (dialogoEspera != null && dialogoEspera.isVisible()) {

            System.out.println("[Vista] Cerrando diálogo de espera y limpiando tablero...");

            // 1. Cerrar ventana
            dialogoEspera.setVisible(false);
            dialogoEspera.dispose();
            dialogoEspera = null;

            // 2. LIMPIAR TABLERO VISUALMENTE
            modeloVista.reiniciarTableroJugador();

        }
         

        this.repaint();

    }

    /**
     * Actualiza el nombre de la carta actual mostrada en la interfaz.
     *
     * @param carta Nombre de la carta.
     */
    public void actualizarNombreCarta(String carta) {
        this.labelNombreCartaActual.setText(carta);
    }

    /**
     * Crea e inserta el panel de tarjeta del jugador principal.
     */
    public void crearPanelTarjeta() {
        //Agregar panel tarjeta jugador principal
        JPanelTarjeta panelTarjeta = new JPanelTarjeta(modeloVista);
        panelTarjeta.setPreferredSize(new Dimension(370, 525));
        panelTableroImagen.setLayout(new BorderLayout());
        panelTableroImagen.add(panelTarjeta, BorderLayout.CENTER);
    }

    /**
     * Crea e inserta el panel de la carta cantada.
     */
    public void crearPanelCarta() {
        // Agregar panel de carta cantada
        JPanelCarta panelCarta = new JPanelCarta(modeloVista, this);
        panelCarta.setPreferredSize(new Dimension(213, 323));
        panelCartaImg.setLayout(new BorderLayout());
        panelCartaImg.add(panelCarta, BorderLayout.CENTER);
    }

    /**
     * Crea e inserta el panel del jugador principal.
     */
    public void crearPanelJugadorPrincipal() {
        //Agregar panel tarjeta jugador principal
        JPanelJugadorPrincipal panelJugadorPrincipal = new JPanelJugadorPrincipal(modeloVista);
        panelJugadorPrincipal.setPreferredSize(new Dimension(453, 111));
        this.panelJugadorPrincipal.setLayout(new BorderLayout());
        this.panelJugadorPrincipal.add(panelJugadorPrincipal, BorderLayout.CENTER);
    }

    /**
     * Carga los paneles de jugadores secundarios, agregando placeholders para
     * mantener un layout uniforme incluso si hay pocos jugadores.
     */
    public void cargarJugadoresSecundarios() {
        List<JugadorVista> jugadores = modeloVista.getJugadoresSecundarios();

        // Contenedor vertical para los "slots"
        JPanel contenedor = new JPanel();
        contenedor.setLayout(new BoxLayout(contenedor, BoxLayout.Y_AXIS));
        contenedor.setOpaque(false);

        // 1) Agrega los jugadores reales
        int count = 0;
        Dimension slotDim = null; // calcularemos el alto con el 1er panel real
        for (JugadorVista j : jugadores) {
            PanelJugadorSecundario item = new PanelJugadorSecundario(j, modeloVista);

            // Que se pegue a la izquierda y no se centre raro
            item.setAlignmentX(JPanel.LEFT_ALIGNMENT);

            // guardamos el alto del primer panel para copiarlo a los vacíos
            if (slotDim == null) {
                // Tomamos su preferredHeight.
                // Si tu panel tiene layout del editor, esto ya trae un alto coherente.
                slotDim = new Dimension(300, item.getPreferredSize().height);
                // ancho "base"; puedes ignorarlo; el importante es el alto
            }

            // deja que se estire a lo ancho si el contenedor lo permite
            item.setMaximumSize(new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height));

            contenedor.add(item);
            count++;
        }

        // 2) Agrega placeholders (vacíos) del MISMO tamaño para empujar hacia arriba
        final int MIN_SLOTS = 4; // <- ajusta cuántos "slots" quieres ver como mínimo
        if (slotDim == null) {
            // Si no hubo jugadores, define un alto base para los vacíos (coherente con tu UI)
            slotDim = new Dimension(300, 200);
        }

        while (count < MIN_SLOTS) {
            JPanel placeholder = crearPlaceholder(slotDim.height);
            placeholder.setAlignmentX(JPanel.LEFT_ALIGNMENT);
            placeholder.setMaximumSize(new Dimension(Integer.MAX_VALUE, slotDim.height));
            contenedor.add(placeholder);
            count++;
        }

        // 3) Monta el contenedor en el panel derecho
        panelJugadoresSecundarios.removeAll();
        panelJugadoresSecundarios.setLayout(new BorderLayout());
        panelJugadoresSecundarios.add(contenedor, BorderLayout.NORTH); // anclado arriba
        panelJugadoresSecundarios.revalidate();
        panelJugadoresSecundarios.repaint();
    }

    /**
     * Crea un panel placeholder con alto fijo para mantener layout uniforme.
     *
     * @param height Alto del placeholder.
     * @return JPanel placeholder.
     */
    private JPanel crearPlaceholder(int height) {
        JPanel p = new JPanel();
        // si prefieres transparente:
        p.setOpaque(false);
        // o si prefieres "en blanco", usa:
        // p.setBackground(Color.WHITE); p.setOpaque(true);

        // Mismo alto que el panel real
        p.setPreferredSize(new Dimension(300, height));
        // Borde opcional muy sutil para conservar el layout visual (puedes quitarlo):
        // p.setBorder(BorderFactory.createEmptyBorder(8, 0, 8, 0));
        return p;
    }

    /**
     * Muestra una alerta modal indicando quién ganó la ronda. Si el usuario es
     * HOST, muestra un botón para continuar. Si es CLIENTE, muestra un mensaje
     * de espera.
     */
    public void mostrarJOptionPaneFinRonda(int ronda, String ganador) {

        String titulo = "Fin de la Ronda " + ronda;
        String mensaje = "¡El jugador " + ganador.toUpperCase() + " ha ganado la ronda!";

        if (modeloVista.isHost()) {
            // --- CASO HOST ---
            Object[] opciones = {"Iniciar Siguiente Ronda"};

            int seleccion = JOptionPane.showOptionDialog(
                    this,
                    mensaje + "\n\nPresiona para continuar la partida.",
                    titulo,
                    JOptionPane.OK_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]
            );

            // SI PRESIONA EL BOTÓN:
            if (seleccion == JOptionPane.OK_OPTION) {
                
                // 1. APAGAR LA BANDERA INMEDIATAMENTE
                // Esto evita que el update() vuelva a abrir la ventana
                modeloVista.limpiarEstadoRonda(); 
                
                // 2. LIMPIAR TABLERO VISUALMENTE
                limpiarTableroVisual(); 

                // 3. ENVIAR ORDEN AL SERVIDOR
                if (oyenteAccion != null) {
                    oyenteAccion.solicitarSiguienteRonda();
                }
            }

        } else {
            // --- CASO CLIENTE (Sin cambios, esto ya estaba bien con el dialogoEspera) ---
            if (dialogoEspera != null && dialogoEspera.isVisible()) return;

            JOptionPane pane = new JOptionPane(
                    mensaje + "\n\nEsperando al anfitrión para continuar...",
                    JOptionPane.INFORMATION_MESSAGE,
                    JOptionPane.DEFAULT_OPTION,
                    null,
                    new Object[]{},
                    null
            );
            dialogoEspera = pane.createDialog(this, titulo);
            dialogoEspera.setDefaultCloseOperation(javax.swing.JDialog.DO_NOTHING_ON_CLOSE);
            dialogoEspera.setModal(false);
            dialogoEspera.setVisible(true);
        }
    }

    /**
     * Pone todas las casillas del jugador principal en falso visualmente para
     * iniciar la nueva ronda.
     */
    private void limpiarTableroVisual() {
         
        var jugador = modeloVista.getJugadorPrincipal();

        if (jugador != null && jugador.getTarjeta() != null) {
            
            boolean[] vacias = new boolean[16];

            modeloVista.actualizarTarjetaJugadorP(vacias);
        }
    }

}
