package Presentacion;

import Controlador.ControladorInicio;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class JPantallaConfigurarPartida extends JFramePadre {

    private ControladorInicio controlador;
    private final ButtonGroup grupoDificultad = new ButtonGroup();
    private final ButtonGroup grupoJugadores = new ButtonGroup();

    /**
     * Creates new form JPantallaConfigurarPartida
     */
    public JPantallaConfigurarPartida() {
        this(null);
    }

    public JPantallaConfigurarPartida(ControladorInicio controlador) {
        this.controlador = controlador;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        configurarGrupos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        panelDificultad = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        labelSubtitulo3 = new javax.swing.JLabel();
        panelNumJugadores = new javax.swing.JPanel();
        labelSubtitulo1 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        panelPuntuacionMax = new javax.swing.JPanel();
        labelSubtitulo2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelPuntuaciones = new javax.swing.JPanel();
        labelSubtitulo5 = new javax.swing.JLabel();
        labelSubtitulo6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        labelSubtitulo7 = new javax.swing.JLabel();
        labelSubtitulo8 = new javax.swing.JLabel();
        labelSubtitulo9 = new javax.swing.JLabel();
        labelSubtitulo10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        panelJugadas = new javax.swing.JPanel();
        labelSubtitulo4 = new javax.swing.JLabel();
        panelJugadasPermitidas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 250, 242));

        jPanel2.setBackground(new java.awt.Color(255, 250, 242));

        labelTitulo.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CREAR NUEVA PARTIDA");

        labelSubtitulo.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo.setText("Selecciona la configuración");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSubtitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubtitulo)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelDificultad.setBackground(new java.awt.Color(255, 232, 195));

        jRadioButton1.setBackground(new java.awt.Color(255, 232, 195));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton1.setText("Básico (10s)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 232, 195));
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton2.setText("Intermedio (7s)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 232, 195));
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton3.setText("Avanzado (4s)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        labelSubtitulo3.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        labelSubtitulo3.setForeground(new java.awt.Color(99, 62, 2));
        labelSubtitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo3.setText("Dificultad");

        javax.swing.GroupLayout panelDificultadLayout = new javax.swing.GroupLayout(panelDificultad);
        panelDificultad.setLayout(panelDificultadLayout);
        panelDificultadLayout.setHorizontalGroup(
            panelDificultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDificultadLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelDificultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDificultadLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(panelDificultadLayout.createSequentialGroup()
                        .addGroup(panelDificultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelDificultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDificultadLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelSubtitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDificultadLayout.setVerticalGroup(
            panelDificultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDificultadLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(panelDificultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDificultadLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(labelSubtitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );

        panelNumJugadores.setBackground(new java.awt.Color(255, 209, 138));

        labelSubtitulo1.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        labelSubtitulo1.setForeground(new java.awt.Color(96, 60, 5));
        labelSubtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo1.setText("Jugadores");

        jRadioButton4.setBackground(new java.awt.Color(255, 209, 138));
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton4.setText("2 Jugadores");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(255, 209, 138));
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton5.setText("3 Jugadores");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(255, 209, 138));
        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jRadioButton6.setText("4 Jugadores");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNumJugadoresLayout = new javax.swing.GroupLayout(panelNumJugadores);
        panelNumJugadores.setLayout(panelNumJugadoresLayout);
        panelNumJugadoresLayout.setHorizontalGroup(
            panelNumJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSubtitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelNumJugadoresLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelNumJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        panelNumJugadoresLayout.setVerticalGroup(
            panelNumJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNumJugadoresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelSubtitulo1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelPuntuacionMax.setBackground(new java.awt.Color(225, 210, 255));

        labelSubtitulo2.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        labelSubtitulo2.setForeground(new java.awt.Color(10, 27, 192));
        labelSubtitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo2.setText("Puntuación Máxima");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelPuntuacionMaxLayout = new javax.swing.GroupLayout(panelPuntuacionMax);
        panelPuntuacionMax.setLayout(panelPuntuacionMaxLayout);
        panelPuntuacionMaxLayout.setHorizontalGroup(
            panelPuntuacionMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSubtitulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPuntuacionMaxLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        panelPuntuacionMaxLayout.setVerticalGroup(
            panelPuntuacionMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntuacionMaxLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelSubtitulo2)
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(255, 250, 242));
        panelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnConfirmar.setBackground(new java.awt.Color(191, 233, 150));
        btnConfirmar.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(0, 42, 0));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(221, 122, 122));
        btnSalir.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 42, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelPuntuaciones.setBackground(new java.awt.Color(226, 211, 188));

        labelSubtitulo5.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        labelSubtitulo5.setForeground(new java.awt.Color(99, 62, 2));
        labelSubtitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo5.setText("PUNTUACIONES");

        labelSubtitulo6.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSubtitulo6.setText("Chorro...................................");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("100");

        labelSubtitulo7.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSubtitulo7.setText("Cuatro Esquinas................");

        labelSubtitulo8.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSubtitulo8.setText("Cruz....................................");

        labelSubtitulo9.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSubtitulo9.setText("Centro....................................");

        labelSubtitulo10.setFont(new java.awt.Font("Sarabun", 2, 18)); // NOI18N
        labelSubtitulo10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSubtitulo10.setText("Llena....................................");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("200");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("300");

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("400");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("1000");

        javax.swing.GroupLayout panelPuntuacionesLayout = new javax.swing.GroupLayout(panelPuntuaciones);
        panelPuntuaciones.setLayout(panelPuntuacionesLayout);
        panelPuntuacionesLayout.setHorizontalGroup(
            panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSubtitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPuntuacionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSubtitulo10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubtitulo9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubtitulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubtitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubtitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6))
                .addGap(6, 6, 6))
        );
        panelPuntuacionesLayout.setVerticalGroup(
            panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntuacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSubtitulo5)
                .addGap(0, 0, 0)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubtitulo6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubtitulo7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubtitulo8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubtitulo9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubtitulo10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelJugadas.setBackground(new java.awt.Color(255, 250, 242));

        labelSubtitulo4.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        labelSubtitulo4.setForeground(new java.awt.Color(50, 125, 67));
        labelSubtitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo4.setText("JUGADAS PERMITIDAS");

        panelJugadasPermitidas.setBackground(new java.awt.Color(255, 250, 242));

        jLabel1.setBackground(new java.awt.Color(255, 250, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PantallaConfiguracion/jugadas.png"))); // NOI18N

        javax.swing.GroupLayout panelJugadasPermitidasLayout = new javax.swing.GroupLayout(panelJugadasPermitidas);
        panelJugadasPermitidas.setLayout(panelJugadasPermitidasLayout);
        panelJugadasPermitidasLayout.setHorizontalGroup(
            panelJugadasPermitidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJugadasPermitidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        panelJugadasPermitidasLayout.setVerticalGroup(
            panelJugadasPermitidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelJugadasLayout = new javax.swing.GroupLayout(panelJugadas);
        panelJugadas.setLayout(panelJugadasLayout);
        panelJugadasLayout.setHorizontalGroup(
            panelJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSubtitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelJugadasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelJugadasPermitidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelJugadasLayout.setVerticalGroup(
            panelJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSubtitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugadasPermitidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPuntuacionMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPuntuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelJugadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPuntuacionMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelJugadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPuntuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (controlador != null) {
            controlador.setPantallaConfig(this);
            controlador.onConfirmarConfig();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (controlador != null) {
            controlador.onSalir();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        notificarCambio();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        notificarCambio();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        notificarCambio();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        notificarCambio();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        notificarCambio();
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        notificarCambio();
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void configurarGrupos() {
        grupoDificultad.add(jRadioButton1);
        grupoDificultad.add(jRadioButton2);
        grupoDificultad.add(jRadioButton3);

        grupoJugadores.add(jRadioButton4);
        grupoJugadores.add(jRadioButton5);
        grupoJugadores.add(jRadioButton6);
    }

    private void notificarCambio() {
        if (controlador != null) {
            controlador.onConfigChanged(getDificultadSeleccionada(), getNumeroJugadoresSeleccionado(),
                    getPuntuacionMaxima(), getPuntuaciones());
        }
    }

    public String getDificultadSeleccionada() {
        if (jRadioButton1.isSelected()) {
            return "BÁSICO";
        }
        if (jRadioButton2.isSelected()) {
            return "INTERMEDIO";
        }
        if (jRadioButton3.isSelected()) {
            return "AVANZADO";
        }
        return null;
    }

    public Integer getNumeroJugadoresSeleccionado() {
        if (jRadioButton4.isSelected()) {
            return 2;
        }
        if (jRadioButton5.isSelected()) {
            return 3;
        }
        if (jRadioButton6.isSelected()) {
            return 4;
        }
        return null;
    }

    public Integer getPuntuacionMaxima() {
        return parsePositiveInteger(jTextField1);
    }

    public Map<String, Integer> getPuntuaciones() {
        Map<String, Integer> puntuaciones = new HashMap<>();
        Integer chorro = parsePositiveInteger(jTextField2);
        Integer cruz = parsePositiveInteger(jTextField3);
        Integer centro = parsePositiveInteger(jTextField4);
        Integer cuatroEsquinas = parsePositiveInteger(jTextField5);
        Integer llena = parsePositiveInteger(jTextField6);

        if (chorro == null || cruz == null || centro == null || cuatroEsquinas == null || llena == null) {
            return null;
        }

        puntuaciones.put("Chorro", chorro);
        puntuaciones.put("Cruz", cruz);
        puntuaciones.put("Centro", centro);
        puntuaciones.put("Cuatro Esquinas", cuatroEsquinas);
        puntuaciones.put("Llena", llena);
        return puntuaciones;
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validación", JOptionPane.ERROR_MESSAGE);
    }

    private Integer parsePositiveInteger(JTextField textField) {
        try {
            int valor = Integer.parseInt(textField.getText().trim());
            return valor > 0 ? valor : null;
        } catch (NumberFormatException ex) {
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelSubtitulo1;
    private javax.swing.JLabel labelSubtitulo10;
    private javax.swing.JLabel labelSubtitulo2;
    private javax.swing.JLabel labelSubtitulo3;
    private javax.swing.JLabel labelSubtitulo4;
    private javax.swing.JLabel labelSubtitulo5;
    private javax.swing.JLabel labelSubtitulo6;
    private javax.swing.JLabel labelSubtitulo7;
    private javax.swing.JLabel labelSubtitulo8;
    private javax.swing.JLabel labelSubtitulo9;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDificultad;
    private javax.swing.JPanel panelJugadas;
    private javax.swing.JPanel panelJugadasPermitidas;
    private javax.swing.JPanel panelNumJugadores;
    private javax.swing.JPanel panelPuntuacionMax;
    private javax.swing.JPanel panelPuntuaciones;
    // End of variables declaration//GEN-END:variables
}
