/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Usuario;

import ConvertidorJSON.EnumTipoEvento;
import ConvertidorJSON.Evento;
import ConvertidorJSON.ToJSON;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import server.Dispatcher;
import server.NetworkFactory;
import server.ReceiverHelper;
import server.Sender;

/**
 *
 * @author jorge
 */
public class SimuladorJugador extends javax.swing.JFrame {

    private static final int PUERTO_SERVER = 4999; // Puerto de conexión
    private static final String SERVER = "localhost"; // tu IP pública

    
    private Socket socket;
    private BlockingQueue<Evento> colaEnvio = new LinkedBlockingQueue<>();
    private BlockingQueue<String> colaRecepcion = new LinkedBlockingQueue<>();
    private Dispatcher dispatcher;
    private ReceiverHelper receiver;
    private String cartaCantada;

    /**
     * Creates new form SimuladorJugador
     */
    public SimuladorJugador() {
        initComponents();
        inicializarRed();
        
    }
    
    private void inicializarRed() {
        try {
            socket = new Socket(SERVER, PUERTO_SERVER);
            System.out.println("Conectado al servidor.");

            // Crear componentes desde la fábrica
            NetworkFactory factory = NetworkFactory.getInstancia();
            Sender sender = factory.crearSender(socket);
            dispatcher = factory.crearDispatcher(colaEnvio, sender);
            receiver = factory.crearReceiverHelper(socket, colaRecepcion);

            // Lanzar hilos
            new Thread(dispatcher).start();
            new Thread(receiver).start();
            new Thread(() -> procesarMensajes()).start();

        } catch (IOException e) {
            System.err.println("Error al conectar: " + e.getMessage());
        }
    }

    private void procesarMensajes() {
    while (true) {
        try {
            String mensaje = colaRecepcion.take(); // Espera un mensaje del servidor

            if (mensaje.startsWith("CARTA_CANTADA:")) {
                cartaCantada = mensaje.substring("CARTA_CANTADA:".length());
                System.out.println("Carta cantada: " + cartaCantada);

            } else if (mensaje.equals("ACIERTAS")) {
                System.out.println("Carta correcta!");
                if ("El gallo".equals(cartaCantada)) {
                    btnCarta1.setBackground(Color.GREEN);
                } else {
                    btnCarta2.setBackground(Color.GREEN);
                }

            } else if (mensaje.equals("FALLAS")) {
                System.out.println("Carta incorrecta!");
            }

        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            break;
        }
    }
}


    private void enviarEvento(EnumTipoEvento tipoEvento, int idJugador, String carta, int posicion) {
        Evento evento = new Evento(tipoEvento, idJugador, carta, posicion);
        colaEnvio.add(evento);
    }
    
    private void cerrarConexion() {
    try {
        if (dispatcher != null) {
            dispatcher.detener();
        }

        if (socket != null && !socket.isClosed()) {
            socket.close();
        }

        System.out.println("Conexión cerrada correctamente.");
    } catch (IOException e) {
        System.err.println("Error al cerrar la conexión: " + e.getMessage());
    }
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCarta1 = new javax.swing.JButton();
        btnCarta2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarta1.setBackground(new java.awt.Color(204, 204, 204));
        btnCarta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarta1.setText("Gallo");
        btnCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta1ActionPerformed(evt);
            }
        });

        btnCarta2.setBackground(new java.awt.Color(204, 204, 204));
        btnCarta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarta2.setText("Estrella");
        btnCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(btnCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta1ActionPerformed
        enviarEvento(EnumTipoEvento.SELECCIONAR_CARTA, 1, "El gallo", 1);

    }//GEN-LAST:event_btnCarta1ActionPerformed

    private void btnCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta2ActionPerformed
        enviarEvento(EnumTipoEvento.SELECCIONAR_CARTA, 2, "La estrella", 2);
    }//GEN-LAST:event_btnCarta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarta1;
    private javax.swing.JButton btnCarta2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
